### ISSUE TITLE
1.48 not on ctan

### ISSUE THREAD

**Issue by kmindi** [borisveytsman/acmart#262] opened 2017-12-08 11:48 UTC

**Comment by borisveytsman** [comment] 2017-12-09 04:27
This is by design.  1.47 is the official version, and 1.48 is the experimental one.  You are welcome to download and test 1.48;  as soon as ACM approves it, it will become official (and will be released to CTAN), and the version on GitHub will become 1.49

**Closed by borisveytsman** 2017-12-09 04:27 UTC

**Comment by kmindi** [comment] 2017-12-09 16:37
But https://www.acm.org/publications/proceedings-template mentions 1.48?
![screenshot-2017-12-9 2017 acm master article template](https://user-images.githubusercontent.com/1949593/33797405-72691cb2-dd07-11e7-9970-8569e58d3099.png)


btw that release policy is not intuitive (rel #214 )

**Comment by borisveytsman** [comment] 2017-12-09 23:49
This looks like an error:  the zip file contains v1.47.
