### ISSUE TITLE
Duplicate year entries in misc and articles in ACM-Reference-Format.bst

### ISSUE THREAD

**Issue by vvdveen** [borisveytsman/acmart#201] opened 2017-08-19 13:53 UTC
When citing an `@Article` or `@Misc`, the year of publication shows up twice when using the ACM-Reference-Format bibliogrpahystyle.

For example:
```
@Misc{aslr,
  title        = "Address Space Layout Randomization {(ASLR)}",
  author       = "{PaX Team}",
  note         = "\url{pax.grsecurity.net/docs/aslr.txt}",
  year         = "2003",
}
```
Results in:
```
PaX Team. 2003. Address Space Layout Randomization (ASLR). (2003). pax.grsecurity.net/docs/aslr.txt.
```

It is unclear to me whether this is a bug or perhaps desired behavior. We fixed it by removing the lines `output.year.check` and `output.day.month.year` from the `FUNCTION { article }` and `FUNCTION { misc }`functions respectively.

**Comment by MatthewFluet** [comment] 2017-08-19 17:33
Duplicate of #151. As noted in that issue, this is how ACM wants references formatted.

**Comment by LeonMeier** [comment] 2017-09-18 12:16
The bug report #151 speaks about articles. But the above is a **MISC**. For example, for Web resources mentioned in the [ACM citation style](https://www.acm.org/publications/authors/reference-formatting), the year need not occur twice (or at all).

**Comment by borisveytsman** [comment] 2017-09-18 23:29
I guess this change requires an ACM decision

**Comment by LeonMeier** [comment] 2017-09-18 23:32
@borisveytsman For the `@MISC` bibentry, I don't think so: their examples are, among others, 

> [2] ACM. Association for Computing Machinery: Advancing Computing as a Science & Profession. Retrieved from http://www.acm.org/.
> 
> [3] Wikipedia. 2017. WikipediA: the Free Encyclopedia. Retrieved from https://www.wikipedia.org/.

**Comment by borisveytsman** [comment] 2017-09-19 13:47
@craig-rodkin Do you want to comment?  Should I change the formatting of misc entries?

**Comment by Craig-Rodkin** [comment] 2017-09-19 13:56
Hi Boris,
It is ok to correct for MISC.

**Closed** 2017-09-23 18:22 UTC
