### ISSUE TITLE
@article year printed twice

### ISSUE THREAD

**Issue by zackw** [borisveytsman/acmart#306] opened 2018-08-10 21:47 UTC
Bibliography entries of type `@article` have their year printed twice, e.g.

``` bib
@article{abdou.2015.cpv,
  author =       {Abdou, AbdelRahman M. and Matrawy, Ashraf and Van
                  Oorschot, Paul C.},
  title =        {{CPV: Delay-based Location Verification for the
                  Internet}},
  journal =      {Transactions on Dependable and Secure Computing},
  publisher =    {IEEE},
  year =         2015,
  volume =       14,
  number =       2,
  pages =        {130--144}
}
```

is rendered as

> AbdelRahman M. Abdou, Ashraf Matrawy, and Paul C. Van Oorschot. **2015.** CPV: Delay-based Location Verification for the Internet. _Transactions on Dependable and Secure Computing_ 14, 2 **(2015)**, 130–144.

(italics in original, boldface highlights the problem)

Is this intentional?

**Comment by MatthewFluet** [comment] 2018-08-10 23:53
Duplicate of #151.  Despite being questioned a number of times, it seems that this is how ACM wants such bibliographic entries to be printed.

**Comment by borisveytsman** [comment] 2019-04-21 17:26
Looks like ACM really wants it this way

**Closed by borisveytsman** 2019-04-21 17:26 UTC
