### ISSUE TITLE
Lemma (and other theorem-environments) give "No counter 'l' defined." error

### ISSUE THREAD

**Issue by MatthewFluet** [borisveytsman/acmart#188] opened 2017-07-27 10:48 UTC
`mwe.tex`:
```
\listfiles
\documentclass{acmart}

\newtheorem{mtflemma}{Lemma}

\begin{document}

\begin{theorem}[Type Safety]
\label{thm:type_safety}
If $\cdot \vdash e : \tau$ and $e \rightarrow^* e'$,
then either $e'$ is a value or there exists $e''$ such that $e' \rightarrow e'$.
\end{theorem}

\begin{mtflemma}[Preservation]
\label{lem:preservation}
If $\cdot \vdash e : \tau$ and $e \rightarrow e'$,
then $\cdot \vdash e : \tau'$.
\end{mtflemma}

\begin{lemma}[Progres]
\label{lem:progress}
If $\cdot \vdash e' : \tau$,
then either $e'$ is a value or there exists $e''$ such that $e' \rightarrow e'$.
\end{lemma}

\cref{thm:type_safety} and \cref{lem:preservation} and \cref{lem:progress}.

\end{document}
```

```
[matthew@shadow tmp]$ pdflatex mwe.tex
This is pdfTeX, Version 3.14159265-2.6-1.40.17 (TeX Live 2016) (preloaded format=pdflatex)
 restricted \write18 enabled.
...

! LaTeX Error: No counter 'l' defined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.20 \begin{lemma}
                  [Progress]
? R
OK, entering \nonstopmode...
...
 *File List*
  acmart.cls    2017/07/09 v1.43 Typesetting articles for Association of Comput
ing Machinery
 xkeyval.sty    2014/12/03 v2.7a package option processing (HA)
 xkeyval.tex    2014/12/03 v2.7a key=value parser (HA)
 xstring.sty    2013/10/13  v1.7c  String manipulations (C Tellechea)
  amsart.cls    2015/03/04 v2.20.2
 amsmath.sty    2016/06/28 v2.15d AMS math features
 amstext.sty    2000/06/29 v2.01 AMS text
  amsgen.sty    1999/11/30 v2.0 generic functions
  amsbsy.sty    1999/11/29 v1.2d Bold Symbols
  amsopn.sty    2016/03/08 v2.02 operator names
    umsa.fd    2013/01/14 v3.01 AMS symbols A
amsfonts.sty    2013/01/14 v3.01 Basic AMSFonts support
microtype.sty    2016/05/14 v2.6a Micro-typographical refinements (RS)
microtype-pdftex.def    2016/05/14 v2.6a Definitions specific to pdftex (RS)
microtype.cfg    2016/05/14 v2.6a microtype main configuration file (RS)
totpages.sty    2005/09/19 v2.00 Totpages Package (muewi)
everyshi.sty    2001/05/15 v3.00 EveryShipout Package (MS)
 environ.sty    2014/05/04 v0.3 A new way to define environments
trimspaces.sty    2009/09/17 v1.1 Trim spaces around a token list
setspace.sty    2011/12/19 v6.7a set line spacing
textcase.sty    2004/10/07 v0.07 Text only upper/lower case changing (DPC)
  natbib.sty    2010/09/13 8.31b (PWD, AO)
hyperref.sty    2016/05/21 v6.83p Hypertext links for LaTeX
hobsub-hyperref.sty    2016/05/16 v1.14 Bundle oberdiek, subset hyperref (HO)
hobsub-generic.sty    2016/05/16 v1.14 Bundle oberdiek, subset generic (HO)
  hobsub.sty    2016/05/16 v1.14 Construct package bundles (HO)
infwarerr.sty    2016/05/16 v1.4 Providing info/warning/error messages (HO)
 ltxcmds.sty    2016/05/16 v1.23 LaTeX kernel commands for general use (HO)
ifluatex.sty    2016/05/16 v1.4 Provides the ifluatex switch (HO)
  ifvtex.sty    2016/05/16 v1.6 Detect VTeX and its facilities (HO)
 intcalc.sty    2016/05/16 v1.2 Expandable calculations with integers (HO)
   ifpdf.sty    2016/05/14 v3.1 Provides the ifpdf switch
etexcmds.sty    2016/05/16 v1.6 Avoid name clashes with e-TeX commands (HO)
kvsetkeys.sty    2016/05/16 v1.17 Key value parser (HO)
kvdefinekeys.sty    2016/05/16 v1.4 Define keys (HO)
pdftexcmds.sty    2016/05/21 v0.22 Utility functions of pdfTeX for LuaTeX (HO)
pdfescape.sty    2016/05/16 v1.14 Implements pdfTeX's escape features (HO)
bigintcalc.sty    2016/05/16 v1.4 Expandable calculations on big integers (HO)
  bitset.sty    2016/05/16 v1.2 Handle bit-vector datatype (HO)
uniquecounter.sty    2016/05/16 v1.3 Provide unlimited unique counter (HO)
letltxmacro.sty    2016/05/16 v1.5 Let assignment for LaTeX macros (HO)
 hopatch.sty    2016/05/16 v1.3 Wrapper for package hooks (HO)
xcolor-patch.sty    2016/05/16 xcolor patch
atveryend.sty    2016/05/16 v1.9 Hooks at the very end of document (HO)
atbegshi.sty    2016/06/09 v1.18 At begin shipout hook (HO)
refcount.sty    2016/05/16 v3.5 Data extraction from label references (HO)
 hycolor.sty    2016/05/16 v1.8 Color options for hyperref/bookmark (HO)
 ifxetex.sty    2010/09/12 v0.6 Provides ifxetex conditional
 auxhook.sty    2016/05/16 v1.4 Hooks for auxiliary files (HO)
kvoptions.sty    2016/05/16 v3.12 Key value format for package options (HO)
  pd1enc.def    2016/05/21 v6.83p Hyperref: PDFDocEncoding definition (HO)
hyperref.cfg    2002/06/06 v1.2 hyperref configuration of TeXLive
   puenc.def    2016/05/21 v6.83p Hyperref: PDF Unicode definition (HO)
     url.sty    2013/09/16  ver 3.4  Verb mode for urls, etc.
 hpdftex.def    2016/05/21 v6.83p Hyperref driver for pdfTeX
rerunfilecheck.sty    2016/05/16 v1.8 Rerun checks for auxiliary files (HO)
cleveref.sty    2013/12/28 v0.19 Intelligent cross-referencing
graphicx.sty    2014/10/28 v1.0g Enhanced LaTeX Graphics (DPC,SPQR)
graphics.sty    2016/05/09 v1.0r Standard LaTeX Graphics (DPC,SPQR)
    trig.sty    2016/01/03 v1.10 sin cos tan (DPC)
graphics.cfg    2016/01/02 v1.10 sample graphics configuration
  pdftex.def    2016/07/10 v0.06j Graphics/color for pdfTeX
  xcolor.sty    2016/05/11 v2.12 LaTeX color extensions (UK)
   color.cfg    2016/01/02 v1.6 sample color configuration
geometry.sty    2010/09/12 v5.6 Page Geometry
manyfoot.sty    2005/09/11 v1.10 Many Footnote Levels Package (NCC)
nccfoots.sty    2005/02/03 v1.2 NCC Footnotes Package (NCC)
   iftex.sty    2013/04/04 v0.2 Provides if(tex) conditional for PDFTeX, XeTeX,
 and LuaTeX
glyphtounicode.tex
    cmap.sty    2008/03/06 v1.0h CMap support: searchable PDF
libertine.sty    2014/11/25 (Bob Tennent) Supports Libertine and Biolinum fonts
 for all LaTeX engines.
textcomp.sty    2005/09/27 v1.99g Standard LaTeX package
  ts1enc.def    2001/06/05 v3.0e (jk/car/fm) Standard LaTeX file
mweights.sty    2013/07/21 (Bob Tennent) Support package for multiple-weight fo
nt packages. 
 fontenc.sty
fontaxes.sty    2014/03/23 v1.0d Font selection axes
LinLibertine_I.tex
     zi4.sty    2016/02/22 v1.10
newtxmath.sty    2016/03/27 v1.466
  binhex.tex
 fontenc.sty
   t1enc.def    2005/09/27 v1.99g Standard LaTeX file
 caption.sty    2016/02/21 v3.3-144 Customizing captions (AR)
caption3.sty    2016/05/22 v1.7-166 caption3 kernel (AR)
   float.sty    2001/11/08 v1.3d Float enhancements (AL)
 comment.sty    
fancyhdr.sty    
T1LinuxLibertineT-TLF.fd    2012/11/26 (autoinst) Font definitions for T1/Linux
LibertineT-TLF.
omlnxlmi.fd    2013/11/19 Fontinst v1.933 font definitions for OML/nxlmi.
omsntxsy.fd    2012/11/14 Fontinst v1.933 font definitions for OMS/ntxsy.
 untxexa.fd    2012/04/16 Fontinst v1.933 font definitions for U/ntxexa.
  ts1cmr.fd    2014/09/29 v2.5h Standard LaTeX font definitions
OT1LinuxLibertineT-TLF.fd    2012/11/26 (autoinst) Font definitions for OT1/Lin
uxLibertineT-TLF.
    umsa.fd    2013/01/14 v3.01 AMS symbols A
    umsb.fd    2013/01/14 v3.01 AMS symbols B
 untxmia.fd    2012/04/16 Fontinst v1.933 font definitions for U/ntxmia.
 untxsym.fd    2015/03/20 Fontinst v1.933 font definitions for U/ntxsym.
 untxsyc.fd    2012/04/12 Fontinst v1.933 font definitions for U/ntxsyc.
 nameref.sty    2016/05/21 v2.44 Cross-referencing by name of section
gettitlestring.sty    2016/05/16 v1.5 Cleanup title references (HO)
     mwe.out
     mwe.out
supp-pdf.mkii
epstopdf-base.sty    2016/05/15 v2.6 Base part for package epstopdf
  grfext.sty    2016/05/16 v1.2 Manage graphics extensions (HO)
epstopdf-sys.cfg    2010/07/13 v1.3 Configuration of (r)epstopdf for TeX Live
 upquote.sty    2012/04/19 v1.3 upright-quote and grave-accent glyphs in verbat
im
  mt-msa.cfg    2006/02/04 v1.1 microtype config. file: AMS symbols (a) (RS)
  mt-msb.cfg    2005/06/01 v1.0 microtype config. file: AMS symbols (b) (RS)
 ***********
```
This is a Fedora 26 system, with all TeX packages (except `acmart`) installed via the Fedora package manager.  Note that there was no error at `\begin{theorem}` or the `\begin{mtflemma}`.

**Comment by borisveytsman** [comment] 2017-07-30 22:14
I cannot reproduce the error:  this compiles fine with the latest code (after changes to theorem env)

```
 *File List*
  acmart.cls    2017/07/30 v1.44 Typesetting articles for Association of Comput
ing Machinery
 xkeyval.sty    2014/12/03 v2.7a package option processing (HA)
 xkeyval.tex    2014/12/03 v2.7a key=value parser (HA)
 xstring.sty    2013/10/13  v1.7c  String manipulations (C Tellechea)
  amsart.cls    2015/03/04 v2.20.2
 amsmath.sty    2016/11/05 v2.16a AMS math features
 amstext.sty    2000/06/29 v2.01 AMS text
  amsgen.sty    1999/11/30 v2.0 generic functions
  amsbsy.sty    1999/11/29 v1.2d Bold Symbols
  amsopn.sty    2016/03/08 v2.02 operator names
    umsa.fd    2013/01/14 v3.01 AMS symbols A
amsfonts.sty    2013/01/14 v3.01 Basic AMSFonts support
microtype.sty    2016/05/14 v2.6a Micro-typographical refinements (RS)
microtype-pdftex.def    2016/05/14 v2.6a Definitions specific to pdftex (RS)
microtype.cfg    2016/05/14 v2.6a microtype main configuration file (RS)
refcount.sty    2016/05/16 v3.5 Data extraction from label references (HO)
 ltxcmds.sty    2016/05/16 v1.23 LaTeX kernel commands for general use (HO)
infwarerr.sty    2016/05/16 v1.4 Providing info/warning/error messages (HO)
totpages.sty    2005/09/19 v2.00 Totpages Package (muewi)
everyshi.sty    2001/05/15 v3.00 EveryShipout Package (MS)
 environ.sty    2014/05/04 v0.3 A new way to define environments
trimspaces.sty    2009/09/17 v1.1 Trim spaces around a token list
setspace.sty    2011/12/19 v6.7a set line spacing
textcase.sty    2004/10/07 v0.07 Text only upper/lower case changing (DPC)
  natbib.sty    2010/09/13 8.31b (PWD, AO)
hyperref.sty    2017/03/14 v6.85a Hypertext links for LaTeX
hobsub-hyperref.sty    2016/05/16 v1.14 Bundle oberdiek, subset hyperref (HO)
hobsub-generic.sty    2016/05/16 v1.14 Bundle oberdiek, subset generic (HO)
  hobsub.sty    2016/05/16 v1.14 Construct package bundles (HO)
ifluatex.sty    2016/05/16 v1.4 Provides the ifluatex switch (HO)
  ifvtex.sty    2016/05/16 v1.6 Detect VTeX and its facilities (HO)
 intcalc.sty    2016/05/16 v1.2 Expandable calculations with integers (HO)
   ifpdf.sty    2017/03/15 v3.2 Provides the ifpdf switch
etexcmds.sty    2016/05/16 v1.6 Avoid name clashes with e-TeX commands (HO)
kvsetkeys.sty    2016/05/16 v1.17 Key value parser (HO)
kvdefinekeys.sty    2016/05/16 v1.4 Define keys (HO)
pdftexcmds.sty    2017/03/19 v0.25 Utility functions of pdfTeX for LuaTeX (HO)
pdfescape.sty    2016/05/16 v1.14 Implements pdfTeX's escape features (HO)
bigintcalc.sty    2016/05/16 v1.4 Expandable calculations on big integers (HO)
  bitset.sty    2016/05/16 v1.2 Handle bit-vector datatype (HO)
uniquecounter.sty    2016/05/16 v1.3 Provide unlimited unique counter (HO)
letltxmacro.sty    2016/05/16 v1.5 Let assignment for LaTeX macros (HO)
 hopatch.sty    2016/05/16 v1.3 Wrapper for package hooks (HO)
xcolor-patch.sty    2016/05/16 xcolor patch
atveryend.sty    2016/05/16 v1.9 Hooks at the very end of document (HO)
atbegshi.sty    2016/06/09 v1.18 At begin shipout hook (HO)
 hycolor.sty    2016/05/16 v1.8 Color options for hyperref/bookmark (HO)
 ifxetex.sty    2010/09/12 v0.6 Provides ifxetex conditional
 auxhook.sty    2016/05/16 v1.4 Hooks for auxiliary files (HO)
kvoptions.sty    2016/05/16 v3.12 Key value format for package options (HO)
  pd1enc.def    2017/03/14 v6.85a Hyperref: PDFDocEncoding definition (HO)
hyperref.cfg    2002/06/06 v1.2 hyperref configuration of TeXLive
   puenc.def    2017/03/14 v6.85a Hyperref: PDF Unicode definition (HO)
     url.sty    2013/09/16  ver 3.4  Verb mode for urls, etc.
 hpdftex.def    2017/03/14 v6.85a Hyperref driver for pdfTeX
rerunfilecheck.sty    2016/05/16 v1.8 Rerun checks for auxiliary files (HO)
cleveref.sty    2013/12/28 v0.19 Intelligent cross-referencing
graphicx.sty    2017/06/01 v1.1a Enhanced LaTeX Graphics (DPC,SPQR)
graphics.sty    2017/06/25 v1.2c Standard LaTeX Graphics (DPC,SPQR)
    trig.sty    2016/01/03 v1.10 sin cos tan (DPC)
graphics.cfg    2016/06/04 v1.11 sample graphics configuration
  pdftex.def    2017/06/24 v1.0g Graphics/color driver for pdftex
  xcolor.sty    2016/05/11 v2.12 LaTeX color extensions (UK)
   color.cfg    2016/01/02 v1.6 sample color configuration
geometry.sty    2010/09/12 v5.6 Page Geometry
manyfoot.sty    2005/09/11 v1.10 Many Footnote Levels Package (NCC)
nccfoots.sty    2005/02/03 v1.2 NCC Footnotes Package (NCC)
   iftex.sty    2013/04/04 v0.2 Provides if(tex) conditional for PDFTeX, XeTeX,
 and LuaTeX
glyphtounicode.tex
    cmap.sty    2008/03/06 v1.0h CMap support: searchable PDF
libertine.sty    2017/03/22 (Bob Tennent) Supports Libertine and Biolinum fonts
 for all LaTeX engines.
textcomp.sty    2017/04/05 v2.0i Standard LaTeX package
  ts1enc.def    2001/06/05 v3.0e (jk/car/fm) Standard LaTeX file
mweights.sty    2017/03/30 (Bob Tennent) Support package for multiple-weight fo
nt packages. 
 fontenc.sty
fontaxes.sty    2014/03/23 v1.0d Font selection axes
LinLibertine_I.tex
     zi4.sty    2017/01/04 v1.112
newtxmath.sty    2017/05/31 v1.524
  binhex.tex
 fontenc.sty
   t1enc.def    2017/04/05 v2.0i Standard LaTeX file
 caption.sty    2016/02/21 v3.3-144 Customizing captions (AR)
caption3.sty    2016/05/22 v1.7-166 caption3 kernel (AR)
   float.sty    2001/11/08 v1.3d Float enhancements (AL)
 comment.sty    
fancyhdr.sty    2017/06/30 v3.9a Extensive control of page headers and footers
  acmthm.sty    2017/07/30 v1.44 Typesetting articles for Association of Comput
ing Machinery
T1LinuxLibertineT-TLF.fd    2017/03/20 (autoinst) Font definitions for T1/Linux
LibertineT-TLF.
omlnxlmi.fd    2013/11/19 Fontinst v1.933 font definitions for OML/nxlmi.
 untxexa.fd    2012/04/16 Fontinst v1.933 font definitions for U/ntxexa.
  ts1cmr.fd    2014/09/29 v2.5h Standard LaTeX font definitions
lmsntxsy.fd    2016/07/02 Fontinst v1.933 font definitions for LMS/ntxsy.
lmxntxexx.fd    2016/07/03 Fontinst v1.933 font definitions for LMX/ntxexx.
OT1LinuxLibertineT-TLF.fd    2017/03/20 (autoinst) Font definitions for OT1/Lin
uxLibertineT-TLF.
    umsa.fd    2013/01/14 v3.01 AMS symbols A
    umsb.fd    2013/01/14 v3.01 AMS symbols B
 untxmia.fd    2016/01/31 Fontinst v1.933 font definitions for U/ntxmia.
 untxsym.fd    2015/03/20 Fontinst v1.933 font definitions for U/ntxsym.
 untxsyc.fd    2012/04/12 Fontinst v1.933 font definitions for U/ntxsyc.
 nameref.sty    2016/05/21 v2.44 Cross-referencing by name of section
gettitlestring.sty    2016/05/16 v1.5 Cleanup title references (HO)
     tmp.out
     tmp.out
supp-pdf.mkii
epstopdf-base.sty    2016/05/15 v2.6 Base part for package epstopdf
  grfext.sty    2016/05/16 v1.2 Manage graphics extensions (HO)
epstopdf-sys.cfg    2010/07/13 v1.3 Configuration of (r)epstopdf for TeX Live
 upquote.sty    2003/08/11 v1.1 Covington's upright-quote modification to verba
tim and verb
  mt-msa.cfg    2006/02/04 v1.1 microtype config. file: AMS symbols (a) (RS)
  mt-msb.cfg    2005/06/01 v1.0 microtype config. file: AMS symbols (b) (RS)
 ***********
```

Could you please check?

**Comment by iradicek** [comment] 2017-08-01 13:45
Hi,

I have the same error on Fedora 25. Also all packages from Fedora package manager, except for acmart cloned from here (commit #d4f9fbc).

`make all` gives:
```

! LaTeX Error: No counter 'd' defined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.201 \begin{definition}
                        [Coalesced Node (C-Node)]A C-node is a set of
? 
! Emergency stop.
```

And MWE from above:
```

! LaTeX Error: No counter 'l' defined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.20 \begin{lemma}
                  [Progres]
```

**Comment by borisveytsman** [comment] 2017-08-01 14:08
Hmmm.  I do not see the error here...

**Comment by borisveytsman** [comment] 2017-08-01 14:23
could you post the minimal example?

**Comment by iradicek** [comment] 2017-08-01 14:30
The first error I get by running `make all` in the freshly cloned repository. The second error is on `mwe.tex` from the first comment above. Here is another example:

```
\documentclass{acmart}
  
\begin{document}

\begin{definition}[Sample definition]
  This is a definition.
\end{definition}

\end{document}
```

The result is (same as for `make all`):
```
! LaTeX Error: No counter 'd' defined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.5 \begin{definition}
                      [Sample definition]
```

Hopefully this helps.

**Comment by iradicek** [comment] 2017-08-01 16:19
I have cross-referenced package versions and one of the differences is `hyperref`, and when I replace Fedora's version `v6.83p` with the newest from CTAN (`v6.85a`) the error seems to go away, for both `make all` and MWE examples. However, I have absolutely no idea why this happens with Fedora's version of `hyperref`.

**Comment by MatthewFluet** [comment] 2017-08-01 22:13
From http://mirrors.rit.edu/CTAN/macros/latex/contrib/hyperref/ChangeLog:

> 2016-06-24  6.83q  David Carlisle
> * 6.83q
> * cleveref support

**Comment by borisveytsman** [comment] 2017-08-01 22:59
Thanks!

Then I can close this issue

**Comment by borisveytsman** [comment] 2017-08-01 23:00
By the way, since I no longer load cleveref by default, this helps with older hyperref :)

**Closed by borisveytsman** 2017-08-01 22:59 UTC

**Comment by MatthewFluet** [comment] 2017-08-01 23:25
But, you are loading `cleveref`: https://github.com/borisveytsman/acmart/blob/master/acmart.dtx#L2350

**Comment by borisveytsman** [comment] 2017-08-01 23:38
I definitely wanted to delete it to close an issue!

Ok, will do it right!

**Comment by iradicek** [comment] 2017-08-02 09:15
Yay, with the latest commit it seems to work without any hacks :)
