### ISSUE TITLE
BibLaTeX & Authoryear citations.

### ISSUE THREAD

**Issue by jfdm** [borisveytsman/acmart#394] opened 2020-05-18 09:18 UTC
Thanks for making the `acmart` development opensource, its a wonderful initiative. 

I think it is great that the `acmart` package provides a BibLaTeX compatible style. However, there are some minor issues with said support which I outline below. If PRs are welcome, I am quite happy to provide them where I can.

## Explicit mention of BibLaTeX numeric style.

+ With out reading the changelog and examining the source package it was not explicitly clear that there was draft support for a BibLaTeX numeric style. People who only use the `acmart` shipped through ctan won't automatically be aware that there is BibLaTeX support.

+ Could the documentation for acmart class be update to **explicitly** mention the draft BibLaTeX support?

## Make naming consistent with NatBib styles.

+ The name of the provided BibLaTeX styles do not reflect the styles provided, and is inconsistent when compared to the provided natbib styles. It is not clear that the style is for numerical citations only.

+ It might be worthwhile changing the name of the `.cbx` and `.bbx` to `acmnumeric.cbx` and `acmnumeric.bbx` to reflect their numerical styling and reflect the existing natbib names. Not to mention one should keep the original name for a few versions for backwards compatibility.
 
## Support for Authoryear BibLaTeX style.

It appears that the support is only for *numerical citations* i.e. acmnumeric. I am wondering if there is a plan to support *both* numerical and authoryear styles?

I do not think this last issue is *too* contentious as it is only bring the BibLaTeX support on par with the natbib support.

**Comment by rdicosmo** [comment] 2022-02-10 12:19
The authoryear bibliographic format is now required by journal styles like PACMPL, so we should really have the corresponding biblatex style.
This will also enable us to use the [biblatex-software](https://ctan.org/pkg/biblatex-software) style extension to support proper citation of software artifacts.

I would be more than willing to lend a hand with other contributors like @jfdm: what is the recommended way to move forward? Should we go for a separate  ACM-Reference-Format-authoryear.{bbx,cbx,.dbx} implementation?

**Comment by borisveytsman** [comment] 2022-02-10 23:46
A good idea.  Can you update the current files adding a switch for authoryear?  THanks!

**Comment by rdicosmo** [comment] 2022-02-11 10:25
> A good idea. Can you update the current files adding a switch for authoryear? THanks!

Great, let's try to bring together some more people, and look into this: @drt24 @jfdm would you be game?

**Comment by jfdm** [comment] 2022-02-11 16:10
From today, I won't *really* be available for a while (annual leave), but happy to chime in on my return.

The key strands here are: Documentation, and generation/inclusion of the `acmauthoryear` style files.

**Comment by drt24** [comment] 2022-02-11 17:38
I won't be able to put significant time into this in the near future but I am happy to try it out and then file patches to fix any bugs I notice once there is a draft implementation. Not got the intricacies of BibLaTeX support in my head any more as I haven't touched it since I did the first implementation.

**Comment by rdicosmo** [comment] 2022-02-15 18:16
A [dedicated repository](https://github.com/rdicosmo/acmart-biblatex) to work on this issue is now set up.
It contains biblatex styles acmnumeric and acmauthoryear (based on @drt24 ACM-Reference-Format biblatex implementation) as well as test files to compare the results w.r.t. the stock bibtex style.

I think I fixed the most outstanding issues (including various improvements to acmnumeric), and support for biblatex-software is now built in, making it straightforward to use the extra bells and whistles for citing and referencing software artifacts.

 @drt24 @jfdm : would you mind giving it a try, and opening issues as needed?

**Comment by rdicosmo** [comment] 2022-02-15 18:17
@borisveytsman @drt24 : what is the license for the ACM-Reference-Format.{bbx,cbx,dbx} files? 
I would love to make acmnumeric and acmauthoryear available under the stock Latex licence, if you agree.

**Comment by borisveytsman** [comment] 2022-02-15 20:13
> @borisveytsman @drt24 : what is the license for the ACM-Reference-Format.{bbx,cbx,dbx} files? I would love to make acmnumeric and acmauthoryear available under the stock Latex licence, if you agree.

My impression is that these files were contributed with the understanding that they are covered by the acmart license, i.e. lppl 


```
% Copyright 2016-2021, Association for Computing Machinery
% This work may be distributed and/or modified under the
% conditions of the LaTeX Project Public License, either
% version 1.3 of this license or (at your option) any
% later version.
```

**Comment by rdicosmo** [comment] 2022-02-15 21:20
> > @borisveytsman @drt24 : what is the license for the ACM-Reference-Format.{bbx,cbx,dbx} files? I would love to make acmnumeric and acmauthoryear available under the stock Latex licence, if you agree.
> 
> My impression is that these files were contributed with the understanding that they are covered by the acmart license, i.e. lppl
> 
> ```
> % Copyright 2016-2021, Association for Computing Machinery
> % This work may be distributed and/or modified under the
> % conditions of the LaTeX Project Public License, either
> % version 1.3 of this license or (at your option) any
> % later version.
> ```

That's perfect, thanks!

**Comment by rdicosmo** [comment] 2022-02-17 18:33
@borisveytsman @drt24 @jdfm @k4rtik @bennn  the first release candidate is ready on https://github.com/rdicosmo/acmart-biblatex/tree/v1.0-rc1
AFAICT, the main differences w.r.t. the ACM-Reference-Format.bst output are for incomplete/malformed bibtex entries, and I would like to consider this as ready to submit for acmart.

Waiting for your feedback before moving forward.

**Comment by k4rtik** [comment] 2022-02-17 19:11
Thanks, Roberto, appreciate the effort to get biblatex support moving! I should be able to give it a shot on Monday.

**Comment by k4rtik** [comment] 2022-02-21 20:28
Hi, @rdicosmo I took a quick look using the main branch of the repo. The first thing I notice is that I don't like the inconsistent hyperlinking/color of author-year citations, here's a screenshot:

<img width="1065" alt="Screen Shot 2022-02-21 at 2 27 57 PM" src="https://user-images.githubusercontent.com/374340/155022364-cabfbf78-c30b-4454-8b75-f8d69efc00a2.png">

Shouldn't the author names be hyperlinked as well?

**Comment by k4rtik** [comment] 2022-02-21 20:38
Oh it brings us to the long-standing issue in biblatex, the latest on which is at https://github.com/plk/biblatex/issues/1024

Basically there two seem to be two solutions:
1. https://tex.stackexchange.com/a/27107/35864 which is what I used in [my own thesis](https://github.com/k4rtik/qhtt-thesis/blob/main/main.tex#L143) some time ago. But apparently, this solution does not link consistently when pre/post notes are involved. I am unsure what acmart style expects in that scenario. I was pretty happy with the rendering of citations in [my thesis](https://ks.cs.uchicago.edu/publication/qhtt-masters/qhtt-masters.pdf).
2. https://tex.stackexchange.com/a/537666/133551 which I have not tested, but from the comments seems isn't ideal either.

Perhaps @borisveytsman can chip in here what is preferable here from ACM's style requirements?

**Comment by k4rtik** [comment] 2022-02-21 21:56
Another issue I observed is that currently on `\textcite`, parentheses are used instead of square brackets.

**Comment by ozross** [comment] 2022-02-21 22:47
Hi Kartik, Boris and others.

I just added a comment at:
   https://github.com/plk/biblatex/issues/1024


Hope this helps.

	Ross


>> From: Kartik Singhal ***@***.***>
>> Date: 22 February 2022 at 7:38:44 am AEDT
>> To: borisveytsman/acmart ***@***.***>
>> Cc: Subscribed ***@***.***>
>> Subject: Re: [borisveytsman/acmart] BibLaTeX & Authoryear citations. (#394)
>> Reply-To: borisveytsman/acmart ***@***.***>
>> 
>> ﻿
>> 
>> Oh it brings us to the long-standing issue in biblatex, the latest on which is at plk/biblatex#1024 <https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fplk%2Fbiblatex%2Fissues%2F1024&data=04%7C01%7Cross.moore%40mq.edu.au%7C90dd0f95b64546e1e98a08d9f57a2332%7C82c514c1a7174087be06d40d2070ad52%7C0%7C0%7C637810727243531105%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=K5vTpDuiaxeJyWMb8zw1prKHoZox0V6lgnyhsASEzOQ%3D&reserved=0>
>> Basically there two seem to be two solutions:
>> 
>> https://tex.stackexchange.com/a/27107/35864 <https://tex.stackexchange.com/a/27107/35864> which is what I used in my own paper <https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fk4rtik%2Fqhtt-thesis%2Fblob%2Fmain%2Fmain.tex%23L143&data=04%7C01%7Cross.moore%40mq.edu.au%7C90dd0f95b64546e1e98a08d9f57a2332%7C82c514c1a7174087be06d40d2070ad52%7C0%7C0%7C637810727243531105%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=LmUQRjAb4ZkCmXgrGQo%2F2c%2FKj7yLRf7CgAcJGVnqfkE%3D&reserved=0> some time ago. But apparently, this solution doesn't work when post notes are involved (I don't know if acmart supports those).
>> https://tex.stackexchange.com/a/537666/133551 <https://tex.stackexchange.com/a/537666/133551> which I have not tested, but from the comments seems isn't ideal either.
>> —
>> Reply to this email directly, view it on GitHub <https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fborisveytsman%2Facmart%2Fissues%2F394%23issuecomment-1047214618&data=04%7C01%7Cross.moore%40mq.edu.au%7C90dd0f95b64546e1e98a08d9f57a2332%7C82c514c1a7174087be06d40d2070ad52%7C0%7C0%7C637810727243531105%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=YVzlDNvp1%2F2KujP8MgJLLTGn3%2F5Hy%2B9jlLvRHSLp%2FqI%3D&reserved=0>, or unsubscribe <https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACYVIOLCHP37CAP3DNHOCFLU4KPEPANCNFSM4ND4XTOQ&data=04%7C01%7Cross.moore%40mq.edu.au%7C90dd0f95b64546e1e98a08d9f57a2332%7C82c514c1a7174087be06d40d2070ad52%7C0%7C0%7C637810727243531105%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=2KVEb96%2BGNf21AKyLbMkMDKk1HYWxOY0HkxyXCgeEb8%3D&reserved=0>.
>> Triage notifications on the go with GitHub Mobile for iOS <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>. 
>> You are receiving this because you are subscribed to this thread.


Dr Ross Moore
Department of Mathematics and Statistics 
12 Wally’s Walk, Level 7, Room 734
Macquarie University, NSW 2109, Australia
T: +61 2 9850 8955  |  F: +61 2 9850 8114
M:+61 407 288 255  |  E: ***@***.***
http://www.maths.mq.edu.au

CRICOS Provider Number 00002J. Think before you print. 
Please consider the environment before printing this email.

This message is intended for the addressee named and may 
contain confidential information. If you are not the intended 
recipient, please delete it and notify the sender. Views expressed 
in this message are those of the individual sender, and are not 
necessarily the views of Macquarie University. <http://mq.edu.au/>
CRICOS Provider Number 00002J. Think before you print. 
Please consider the environment before printing this email.

This message is intended for the addressee named and may 
contain confidential information. If you are not the intended 
recipient, please delete it and notify the sender. Views expressed 
in this message are those of the individual sender, and are not 
necessarily the views of Macquarie University.
 <http://mq.edu.au/>

**Comment by rdicosmo** [comment] 2022-02-22 13:09
> Another issue I observed is that currently on `\textcite`, parentheses are used instead of square brackets.



> Thanks, Roberto, appreciate the effort to get biblatex support moving! I should be able to give it a shot on Monday.

Hi @k4rtik thanks for having a look. I'll comment on the various issues below

**Comment by rdicosmo** [comment] 2022-02-22 13:16
> Another issue I observed is that currently on `\textcite`, parentheses are used instead of square brackets.

As far as I can tell, this is indeed the intended behaviour: \textcite is for discoursive citations flowing inside the text, here the parentheses are around the year, not the citation (and by the way, the original acmart does not support \textcite).
I added a few more examples in the main-acmauthoryear.tex test file, to showcase the different use cases.

**Comment by k4rtik** [comment] 2022-02-22 13:17
> the original acmart does not support \textcite

I believe it supports the equivalent `\citet` command from natbib. The behavior there is to link the author names.

**Comment by rdicosmo** [comment] 2022-02-22 13:30
> Hi Kartik, Boris and others. I just added a comment at: [plk/biblatex#1024](https://github.com/plk/biblatex/issues/1024) Hope this helps. Ross

Thanks @k4rtik and @ozross for looking into this. If I understand well, this is a general biblatex issue, and not specific to the acm biblatex styles, so this should not be a blocker to merge the proposed styles into acmart: authors/editors may decide to add any of the two mentioned workarounds directly in the template .tex files.

But if there is consensus that we want to preload one of these workarounds directly in the acmart styles, I would be more than happy to merge a PR into acmauthoryear.bbx :-)

**Comment by rdicosmo** [comment] 2022-02-22 13:34
> > the original acmart does not support \textcite
> 
> I believe it supports the equivalent `\citet` command from natbib. The behavior there is to link the author names.

Oh, ok thanks! will look into this.

**Comment by k4rtik** [comment] 2022-02-22 13:36
I added usage of `citet` and `parencite` to your additional tests (biblatex supports `citet` and `citep` from natbib for compatibility, but its preferred commands are `textcite` and `parencite`), this is how it renders currently:

<img width="1220" alt="Screen Shot 2022-02-22 at 7 32 16 AM" src="https://user-images.githubusercontent.com/374340/155142478-66052865-2412-4f8d-b8aa-4f75c5da6f29.png">

AFAIK from the current bibtex/natbib implementation of acmart, all of the above should use square brackets (instead of parens) and be linked especially in case of `citeauthor` and `citeyear*`.

---

Here's equivalent bibtex for comparison:
<img width="954" alt="Screen Shot 2022-02-22 at 7 39 44 AM" src="https://user-images.githubusercontent.com/374340/155143751-2c7e97b0-b9d5-4cf6-9e79-05f2783cdea8.png">

(The ? is for software citation that is not yet supported)

Personally, I vastly prefer the latter rendering. But I am willing to compromise for biblatex support if we don't reach a consensus on using either of the workarounds.

**Comment by k4rtik** [comment] 2022-02-22 13:58
Another observation from the comparison above: we should probably inherit from biblatex's `authoryear-comp` to merge entries for the same authors, but it seems to break some of these tests (I don't know why).

**Comment by rdicosmo** [comment] 2022-02-22 16:11
Thanks to @k4rtik's contribution, we are probably pretty close to total compatibility with the original bibtex style!
@borisveytsman @ozross @drt24 @jdfm @bennn : would you mind looking at the test files main-bibtex.pdf, main-acmauthoryear.pdf and main-acmnumeric.pdf that you can produce from https://github.com/rdicosmo/acmart-biblatex/ and see if you spot anything else that needs to be done?

**Comment by k4rtik** [comment] 2022-02-22 16:48
> Another observation from the comparison above: we should probably inherit from biblatex's `authoryear-comp` to merge entries for the same authors, but it seems to break some of these tests (I don't know why).

I would still want to see if we can resolve this issue as well. Perhaps someone with more experience than me may want to tackle this. Some discussion here: https://tex.stackexchange.com/questions/27607/biblatex-authoryear-comp-and-hyperlinks

**Comment by bennn** [comment] 2022-02-23 03:41
I have a build error since commit `b2eb5a75`. Details below:

<details><summary>Bibliography macro 'date+extradate' undefined.</summary>
Running TexLive 2017

```

Package biblatex Warning: No driver for entry type 'dataset'.
(biblatex)                Using fallback driver on input line 224.


Package biblatex Warning: No driver for entry type 'eprint'.
(biblatex)                Using fallback driver on input line 224.


Package biblatex Warning: No driver for entry type 'eprint'.
(biblatex)                Using fallback driver on input line 224.


! Package biblatex Error: Bibliography macro 'date+extradate' undefined.

See the biblatex package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.225 
      
? 
```
</details>

**Comment by rdicosmo** [comment] 2022-02-23 09:22
> I have a build error since commit `b2eb5a75`. Details below:
> 
> Bibliography macro 'date+extradate' undefined.

Thanks @bennn for spotting this: newer versions of biblatex introduced date+extradate in place of the old date+extrayear macro, hence your compilation error with TeXLive 2017.
I pushed a new version with some forward compatibility code: would you mind testing it?

**Comment by bennn** [comment] 2022-02-25 03:23
`make` gives a new error now (on commit [20d6e49](https://github.com/rdicosmo/acmart-biblatex/commit/20d6e49e5c9)):

```
$ make
texfot pdflatex main-acmauthoryear.tex
/Library/TeX/texbin/texfot: invoking: pdflatex main-acmauthoryear.tex
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017) (preloaded format=pdflatex)
! Undefined control sequence.
l.14 \ifbibmacroundef
! Emergency stop.
l.14 \ifbibmacroundef
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on main-acmauthoryear.log.
make: *** [main-acmauthoryear.pdf] Error 1
```

**Comment by rdicosmo** [comment] 2022-02-25 11:04
> ifbibmacroundef

Well, now I'm curious: \ifbibmacroundef was in BibLaTeX earlier than TeXLive 2017 :-)

This is what I see in Biblatex 3.7 (December 2016)

```
$ grep ifbibmacroun tex/latex/biblatex/biblatex.sty
\def\blx@imc@ifbibmacroundef#1{%
  \ifbibmacroundef \iffieldundef \iffieldxref \iflistequalcs \iflistequals
    \def\ifbibmacroundef#1{\blx@TE{\blx@imc@ifbibmacroundef{#1}}}%
```

May you check where is the biblatex.sty file that is used in your compilation, and just "grep ifbibmacroundef biblatex.sty" once you find it?
If the macro is not there, I would like to know the date of that file :-)

**Comment by rdicosmo** [comment] 2022-02-25 13:22
@bennn may you try this branch?
https://github.com/rdicosmo/acmart-biblatex/tree/retrofix

**Comment by bennn** [comment] 2022-02-26 01:52
Much better --- that branch builds 3 pdfs.

The `acmauthoryear` and `acmnumeric` documents look good. The bibtex one didn't handle the SW references correctly:

![Screen Shot 2022-02-25 at 21 05 24](https://user-images.githubusercontent.com/1731829/155824328-dcf8d4db-2d80-4113-ad39-f29e0ba318f1.png)

**Comment by rdicosmo** [comment] 2022-02-26 18:03
> Much better --- that branch builds 3 pdfs.

Ok, great. I pushed another version of the forward compatibility code to the same branch (more defensive programming :-))
If you can confirm that it works for you, I'll merge it in main.

**Comment by rdicosmo** [comment] 2022-02-26 18:05
> The `acmauthoryear` and `acmnumeric` documents look good. The bibtex one didn't handle the SW references correctly:
> 
> ![Screen Shot 2022-02-25 at 21 05 24](https://user-images.githubusercontent.com/1731829/155824328-dcf8d4db-2d80-4113-ad39-f29e0ba318f1.png)

This is expected: the advanced SW entries handling is only supported in biblatex. Support in bibtex would require to change the .bst file, that I would like to leave to others to do ;-)

**Comment by bennn** [comment] 2022-02-27 02:17
Yes, the new version still works for me ([9afd965](https://github.com/rdicosmo/acmart-biblatex/commit/9afd965)).

I don't see anything more to improve in the `acmauthoryear` pdf!

PS just noticed your question about `ifbibmacroundef`. I have the same grep results as Biblatex 3.7:
```
$ grep "ifbibmacroun" /usr/local/texlive/2017/texmf-dist/tex/latex/biblatex/biblatex.sty
\def\blx@imc@ifbibmacroundef#1{%
  \ifbibmacroundef \iffieldundef \iffieldxref \iflistequalcs \iflistequals
    \def\ifbibmacroundef#1{\blx@TE{\blx@imc@ifbibmacroundef{#1}}}%
```

**Comment by rdicosmo** [comment] 2022-02-28 09:18
> Yes, the new version still works for me ([9afd965](https://github.com/rdicosmo/acmart-biblatex/commit/9afd965)).

Thanks, the relevant change is now merged in main!

> I don't see anything more to improve in the `acmauthoryear` pdf!

@k4rtik : should we consider we are good to go, or do you want more time to try ang get the -comp citation style up and running?

**Comment by k4rtik** [comment] 2022-02-28 15:18
I have it [working](https://gist.github.com/k4rtik/0cfa74a3ab2e3d72261a182945d5423c) for all except the `\textcite` commands following the patch at https://tex.stackexchange.com/a/27615/133551

For `textcite`, the solution given in that answer gives me the following error:
```
! Undefined control sequence. l.15896 \blx
                                          @secinit
```
which is driving me crazy. Checking if I can manually fix it.

**Comment by k4rtik** [comment] 2022-02-28 16:55
I realized I didn't need that anyway, PR at https://github.com/rdicosmo/acmart-biblatex/pull/6

**Comment by rdicosmo** [comment] 2022-02-28 17:50
> I realized I didn't need that anyway, PR at [rdicosmo/acmart-biblatex#6](https://github.com/rdicosmo/acmart-biblatex/pull/6)

Perfect, thanks! we are now pretty ready to go!

**Comment by rdicosmo** [comment] 2022-02-28 18:00
@borisveytsman: we are delighted to report that, with the great help of @k4rtik and testing from @bennn, we have now a fully functional biblatex implementation of _both the acmnumeric and the acmauthoryear citation styles_, with the added bonus of an embedded full support of the software citation styles from _biblatex-software_.

You can test the tagged release candidate here https://github.com/rdicosmo/acmart-biblatex/tree/v1.0-rc2

The next step will be to open a pull request wrt acmart to include these additional biblatex style files.

Your guidance would be very welcome if you want also some variant of the test files main-acmnumeric.tex and main-acmauthoryear.tex to be added.

**Comment by k4rtik** [comment] 2022-03-01 05:19
cc'ing @drt24 as well to try the RC2. It will be good to have more eyes/tests to ensure we have reached full compatibility.

**Comment by rdicosmo** [comment] 2022-03-03 11:13
A new RC is out here: https://github.com/rdicosmo/acmart-biblatex/releases/tag/v1.0-rc3
No changes to the acmart part, I simply aligned the RC with the latest biblatex-software release.

**Comment by drt24** [comment] 2022-03-03 20:59
Don't wait for me. I am so far behind I won't get this far down my TODO list for months.

**Comment by jfdm** [comment] 2022-03-23 09:33
Apologies for not responding so promptly! I fully support this, however as with @drt24 please do not wait for me. I am snowed under with work as well. But very appreciative that this has been action'd so well!

**Comment by jfdm** [comment] 2022-03-23 10:19
I see #462 includes the support for BibLaTeX. I am happy for this issue to be closed now. Thanks to all involved with this. I am sorry I was not able to help more.

**Comment by rdicosmo** [comment] 2022-03-24 09:00
Happy to see we have now this solved, thanks @drt24 for the first version of biblatex support, @jfdm for having opened this, to @k4rtik for great help in developing the full fledged solution, and to @bennn for bringing me here and testing the results!

@borisveytsman: thanks for accepting the contribution, it seems this issue can be successfully closed now :-)

**Comment by borisveytsman** [comment] 2022-03-24 17:47
I am grateful to you guys for solving this

**Closed by borisveytsman** 2022-03-24 17:47 UTC
