### ISSUE TITLE
textcomp vs TS1 font encoding

### ISSUE THREAD

**Issue by fare** [borisveytsman/acmart#74] opened 2017-01-17 14:36 UTC
When I try to use ccsdesc, I get the following error:
```
! Package textcomp Error: Symbol \textrightarrow not provided by
(textcomp)                font family ptm in TS1 encoding.
(textcomp)                Default family used instead.
```
It can be worked around by changing the fonts with, e.g.:
```
\usepackage{tgpagella}
```
But that defeats the entire purpose of the class file wrt fonts.

NB: Using commit acmart d21923a0301a8f741cb8e8911d069e340acee76a with pdfTeX 3.14159265-2.6-1.40.17 (TeX Live 2016/NixOS.org), using my [Racket Scribble acmart package](https://github.com/fare/acmart) to compile my [asdf2017](https://github.com/fare/asdf2017) article.

**Comment by fare** [comment] 2017-01-17 14:40
I find that using
```
\PassOptionsToPackage{warn}{textcomp}
```
because I call the `\documentclass` works. Can you use this option to textcomp in your `acmart.dtx` ?

**Comment by borisveytsman** [comment] 2017-01-22 23:45
It looks like you might have an old version of the fonts or textcomp.

Could you add in the beginning of your file (before \documentclass) the command \listfiles, run latex and send me the log?

**Comment by fare** [comment] 2017-01-23 04:08
I'm using NixOS, which bases its TeX support on a texlive release from 2016:
```
This is pdfTeX, Version 3.14159265-2.6-1.40.17 (TeX Live 2016/NixOS.org) (preloaded format=pdflatex)
```
File `/nix/store/wy6pkjr2ibv4w9h4g2nagcr8c4v1vsyr-texlive-combined-full-2016/share/texmf/tex/latex/base/textcomp.sty` has sha256 `732e2ba204d17c2d83098d4f8535529d67c48d14f2a07c67f3801fbabec43581` and says (selecting specific lines):
```
%% The original source files were:
%% ltoutenc.dtx  (with options: `TS1sty')
\ProvidesPackage{textcomp}[2005/09/27 v1.99g Standard LaTeX package]
```
The `*File List*` output is:
```
  acmart.cls    2017/01/07 v1.28 Typesetting articles for Association of Comput
ing Machinery
 xkeyval.sty    2014/12/03 v2.7a package option processing (HA)
 xkeyval.tex    2014/12/03 v2.7a key=value parser (HA)
  amsart.cls    2015/03/04 v2.20.2
 amsmath.sty    2016/03/10 v2.15b AMS math features
 amstext.sty    2000/06/29 v2.01 AMS text
  amsgen.sty    1999/11/30 v2.0 generic functions
  amsbsy.sty    1999/11/29 v1.2d Bold Symbols
  amsopn.sty    2016/03/08 v2.02 operator names
    umsa.fd    2013/01/14 v3.01 AMS symbols A
amsfonts.sty    2013/01/14 v3.01 Basic AMSFonts support
microtype.sty    2016/05/14 v2.6a Micro-typographical refinements (RS)
microtype-pdftex.def    2016/05/14 v2.6a Definitions specific to pdftex (RS)
microtype.cfg    2016/05/14 v2.6a microtype main configuration file (RS)
totpages.sty    2005/09/19 v2.00 Totpages Package (muewi)
everyshi.sty    2001/05/15 v3.00 EveryShipout Package (MS)
 environ.sty    2014/05/04 v0.3 A new way to define environments
trimspaces.sty    2009/09/17 v1.1 Trim spaces around a token list
  natbib.sty    2010/09/13 8.31b (PWD, AO)
hyperref.sty    2016/05/21 v6.83p Hypertext links for LaTeX
hobsub-hyperref.sty    2016/05/16 v1.14 Bundle oberdiek, subset hyperref (HO)
hobsub-generic.sty    2016/05/16 v1.14 Bundle oberdiek, subset generic (HO)
  hobsub.sty    2016/05/16 v1.14 Construct package bundles (HO)
infwarerr.sty    2016/05/16 v1.4 Providing info/warning/error messages (HO)
 ltxcmds.sty    2016/05/16 v1.23 LaTeX kernel commands for general use (HO)
ifluatex.sty    2016/05/16 v1.4 Provides the ifluatex switch (HO)
  ifvtex.sty    2016/05/16 v1.6 Detect VTeX and its facilities (HO)
 intcalc.sty    2016/05/16 v1.2 Expandable calculations with integers (HO)
   ifpdf.sty    2016/05/14 v3.1 Provides the ifpdf switch
etexcmds.sty    2016/05/16 v1.6 Avoid name clashes with e-TeX commands (HO)
kvsetkeys.sty    2016/05/16 v1.17 Key value parser (HO)
kvdefinekeys.sty    2016/05/16 v1.4 Define keys (HO)
pdftexcmds.sty    2016/05/21 v0.22 Utility functions of pdfTeX for LuaTeX (HO)
pdfescape.sty    2016/05/16 v1.14 Implements pdfTeX's escape features (HO)
bigintcalc.sty    2016/05/16 v1.4 Expandable calculations on big integers (HO)
  bitset.sty    2016/05/16 v1.2 Handle bit-vector datatype (HO)
uniquecounter.sty    2016/05/16 v1.3 Provide unlimited unique counter (HO)
letltxmacro.sty    2016/05/16 v1.5 Let assignment for LaTeX macros (HO)
 hopatch.sty    2016/05/16 v1.3 Wrapper for package hooks (HO)
xcolor-patch.sty    2016/05/16 xcolor patch
atveryend.sty    2016/05/16 v1.9 Hooks at the very end of document (HO)
atbegshi.sty    2016/06/09 v1.18 At begin shipout hook (HO)
refcount.sty    2016/05/16 v3.5 Data extraction from label references (HO)
 hycolor.sty    2016/05/16 v1.8 Color options for hyperref/bookmark (HO)
 ifxetex.sty    2010/09/12 v0.6 Provides ifxetex conditional
 auxhook.sty    2016/05/16 v1.4 Hooks for auxiliary files (HO)
kvoptions.sty    2016/05/16 v3.12 Key value format for package options (HO)
  pd1enc.def    2016/05/21 v6.83p Hyperref: PDFDocEncoding definition (HO)
hyperref.cfg    2002/06/06 v1.2 hyperref configuration of TeXLive
   puenc.def    2016/05/21 v6.83p Hyperref: PDF Unicode definition (HO)
     url.sty    2013/09/16  ver 3.4  Verb mode for urls, etc.
 hpdftex.def    2016/05/21 v6.83p Hyperref driver for pdfTeX
rerunfilecheck.sty    2016/05/16 v1.8 Rerun checks for auxiliary files (HO)
graphicx.sty    2014/10/28 v1.0g Enhanced LaTeX Graphics (DPC,SPQR)
graphics.sty    2016/06/02 v1.0s Standard LaTeX Graphics (DPC,SPQR)
    trig.sty    2016/01/03 v1.10 sin cos tan (DPC)
graphics.cfg    2016/06/04 v1.11 sample graphics configuration
  pdftex.def    2016/06/17 v0.06h Graphics/color for pdfTeX
  xcolor.sty    2016/05/11 v2.12 LaTeX color extensions (UK)
   color.cfg    2016/01/02 v1.6 sample color configuration
geometry.sty    2010/09/12 v5.6 Page Geometry
manyfoot.sty    2005/09/11 v1.10 Many Footnote Levels Package (NCC)
nccfoots.sty    2005/02/03 v1.2 NCC Footnotes Package (NCC)
libertine.sty    2014/11/25 (Bob Tennent) Supports Libertine and Biolinum fonts
 for all LaTeX engines.
textcomp.sty    2005/09/27 v1.99g Standard LaTeX package
  ts1enc.def    2001/06/05 v3.0e (jk/car/fm) Standard LaTeX file
mweights.sty    2013/07/21 (Bob Tennent) Support package for multiple-weight fo
nt packages. 
 fontenc.sty
fontaxes.sty    2014/03/23 v1.0d Font selection axes
LinLibertine_I.tex
     zi4.sty    2016/02/22 v1.10
newtxmath.sty    2016/03/27 v1.466
  binhex.tex
 caption.sty    2016/02/21 v3.3-144 Customizing captions (AR)
caption3.sty    2016/05/22 v1.7-166 caption3 kernel (AR)
   float.sty    2001/11/08 v1.3d Float enhancements (AL)
 comment.sty    
fancyhdr.sty    
OT1LinuxLibertineT-TLF.fd    2012/11/26 (autoinst) Font definitions for OT1/Lin
uxLibertineT-TLF.
 relsize.sty    2013/03/29 ver 4.1
 mathabx.sty    2003/07/29 v0.0 Non-standard LaTeX package mathabx
 wasysym.sty    2003/10/30 v2.0 Wasy-2 symbol support package
  framed.sty    2011/10/22 v 0.96: framed or shaded text with page breaks
hyphenat.sty    2009/09/02 v2.3c hyphenation utilities
tocstyle.sty    2016/04/12 v0.2h-alpha KOMA-Script package (versatile toc style
s)
     CJK.sty    2015/04/18 4.8.4
 MULEenc.sty    2015/04/18 4.8.4
    calc.sty    2014/10/28 v4.3 Infix arithmetic (KKT,FJ)
omlnxlmi.fd    2013/11/19 Fontinst v1.933 font definitions for OML/nxlmi.
omsntxsy.fd    2012/11/14 Fontinst v1.933 font definitions for OMS/ntxsy.
  ts1cmr.fd    2014/09/29 v2.5h Standard LaTeX font definitions
  ot1ptm.fd    2001/06/04 font definitions for OT1/ptm.
    umsa.fd    2013/01/14 v3.01 AMS symbols A
    umsb.fd    2013/01/14 v3.01 AMS symbols B
 untxmia.fd    2012/04/16 Fontinst v1.933 font definitions for U/ntxmia.
 untxsym.fd    2015/03/20 Fontinst v1.933 font definitions for U/ntxsym.
 untxsyc.fd    2012/04/12 Fontinst v1.933 font definitions for U/ntxsyc.
 untxexa.fd    2012/04/16 Fontinst v1.933 font definitions for U/ntxexa.
   uwasy.fd    2003/10/30 v2.0 Wasy-2 symbol font definitions
  mt-ptm.cfg    2006/04/20 v1.7 microtype config. file: Times (RS)
 nameref.sty    2016/05/21 v2.44 Cross-referencing by name of section
gettitlestring.sty    2016/05/16 v1.5 Cleanup title references (HO)
asdf2017.out
asdf2017.out
supp-pdf.mkii
epstopdf-base.sty    2016/05/15 v2.6 Base part for package epstopdf
  grfext.sty    2016/05/16 v1.2 Manage graphics extensions (HO)
epstopdf-sys.cfg    2010/07/13 v1.3 Configuration of (r)epstopdf for TeX Live
 upquote.sty    2012/04/19 v1.3 upright-quote and grave-accent glyphs in verbat
im
  ot1zi4.fd    2014/06/22 OT1/zi4 (Inconsolata)
OT1LinuxBiolinumT-TLF.fd    2012/11/26 (autoinst) Font definitions for OT1/Linu
xBiolinumT-TLF.
  mt-msa.cfg    2006/02/04 v1.1 microtype config. file: AMS symbols (a) (RS)
  mt-msb.cfg    2005/06/01 v1.0 microtype config. file: AMS symbols (b) (RS)
  ts1ptm.fd    2001/06/04 font definitions for TS1/ptm.
  mt-cmr.cfg    2013/05/19 v2.2 microtype config. file: Computer Modern Roman (
RS)
 ***********
```

**Comment by borisveytsman** [comment] 2017-01-23 04:28
Hmm.  My version of textcomp is

\ProvidesPackage{textcomp}
 [2016/06/19 v1.99m
                 Standard LaTeX package]

I cannot reproduce your error msg here...

**Comment by fare** [comment] 2017-01-23 04:58
I downloaded `ltoutenc.dtx` and `ltoutenc.ins` from `https://anorien.csc.warwick.ac.uk/mirrors/CTAN/macros/latex/base/` and used them to generate a new `textcomp.sty` that I checked was loaded instead of that from TeX live 2016, but I found that I still needed the same workaround as in my above comment https://github.com/borisveytsman/acmart/issues/74#issuecomment-273185494

**Comment by fare** [comment] 2017-01-23 05:00
Indeed, when I diff the `textcomp.sty` I just created from that from TeX live, I see that all that changed was the version number. Whatever changed in `ltoutenc.dtx` didn't affect `textcomp.sty`.

**Comment by krono** [comment] 2017-01-23 08:50
@fare In your initial report, the error says “    font family ptm in TS1 encoding.”.
`ptm` is the Times font, and not the Libertine font that is used in `acmart`.

Can you please check that you do _not_ use `\usepackage{times}` or `\usepackage{mathptmx}` or similar?

**Comment by fare** [comment] 2017-01-23 13:00
Oh. Racket Scribble, the tool I use to generate LaTeX inserts a `\renewcommand{\rmdefault}{ptm}` which is probably the culprit. I'll consult with the authors as to how to avoid generating that. Thanks a lot!

**Comment by krono** [comment] 2017-01-23 15:41
The `renewcommand` is activated in `share/pkgs/scribble-lib/scribble/scribble.tex`, the scribble prefix file. Maybe you need your own? (cf http://docs.racket-lang.org/scribble/config-style.html?q=latex).

Also, scribble has a `scribble/sigplan` language with a dedicated style. I think, they'll add a `scribble/acmart` soonish, especially if you ask them

**Comment by borisveytsman** [comment] 2017-01-23 16:28
Thanks to krono for investigating this!  You have better eyes than I do.

I am closing this issue as solved.

**Comment by fare** [comment] 2017-01-23 17:20
Thanks to all three of you for your help!

Yes, I'm one of those trying to add acmart support to Scribble as I go, with no prior experience at it. Maybe I can ask myself to make it happen faster...

**Comment by borisveytsman** [comment] 2017-01-23 17:48
Let me know if you need any help!

**Comment by fare** [comment] 2017-01-24 03:26
You already helped tremendously. Thanks a lot!

I didn't yet find a way to disable this `\renewcommand{\rmdefault}{ptm}` --- but until I get help from Scribble maintainers, I've used `\renewcommand{\rmdefault}{LinuxLibertineT-OsF}` to restore the libertine fonts after Scribble overrode them.

**Comment by sjmackenzie** [comment] 2019-04-22 06:00
Any movement on this? I'm suffering from this affliction now.

It pretty much renders the entire generation of a pdf useless when using nixos and scribble.

**Comment by borisveytsman** [comment] 2019-04-22 21:29
Try`\AtBeginDocument{\renewcommand{\rmdefault}{LinuxLibertineT-OsF}}`

**Comment by sjmackenzie** [comment] 2019-04-24 13:19
Actually this nix expression solved the problem:
``` nix
{ nixpkgs ?  <nixpkgs>
, pkgs ? import nixpkgs {}
}:
with pkgs;
let
latex = texlive.combine {
  inherit (texlive)
    scheme-basic
    mathabx
    wasysym
    framed
    hyphenat
    metafont
    collection-fontsrecommended
    relsize
    ;};
in
pkgs.mkShell {
  buildInputs = [
    racket
    latex
  ];
}
```

**Comment by rionda** [comment] 2020-02-03 13:52
I'm having a similar issue and I'm pretty sure all my packages are up to date (I just run the TeXLive upgrade utility):

```
Package textcomp Error: Symbol \textrightarrow not provided by
(textcomp)                font family LinuxLibertineT-TLF in TS1 encoding.
(textcomp)                Default family used instead.
```

I tried to put the line suggested by @borisveytsman at the top of my .tex file (or does it go somewhere else?) but no success.

**Comment by borisveytsman** [comment] 2020-02-05 21:05
Looks like the last upgrade of kernel broke compatibility.  Sigh

**Closed** 2020-02-05 21:07 UTC

**Comment by rionda** [comment] 2020-02-05 21:41
Thank you @borisveytsman .

**Comment by nictilly** [comment] 2020-02-06 04:47
This fix causes the arrow to come from the default font and is therefore a different arrow than the one from Libertine.

**Comment by borisveytsman** [comment] 2020-02-07 00:50
You are right.  OK, another version

**Comment by ccshan** [comment] 2020-02-12 19:33
Are these the same issue?
```
! LaTeX Error: Command \textrightarrow unavailable in encoding T1.
```
```
! LaTeX Error: Command \textminus unavailable in encoding T1.
```

**Comment by borisveytsman** [comment] 2020-02-22 22:06
Yes.  Can you give an MWE for this error?

**Comment by ccshan** [comment] 2020-02-22 22:48
I'm sorry but upgrading to latex 2020-02-02 PL 2 seems to have fixed it. Do you still want a MWE for PL 1?
