### ISSUE TITLE
Issue with German Umlauts

### ISSUE THREAD

**Issue by mrigger** [borisveytsman/acmart#351] opened 2019-06-05 19:12 UTC
I have an issue with German umlauts in the `\author` command.

Consider the following file:

``` 
\documentclass[sigconf,screen]{acmart} 
\usepackage[utf8]{inputenc}
\begin{document}
\author{ö}
\title{test}
\maketitle
\end{document}
``` 
When using an old version of acmart (acmart 2017/04/13 v1.35), I can successfully compile the file using pdflatex (version pdfTeX 3.14159265-2.6-1.40.19 (TeX Live 2019/dev/Debian)) on Ubuntu 18.10. However, when compiling with one of the recent versions (e.g., acmart v1.60 (2019-04-22)), I get the following error:

```
! Undefined control sequence.
\MT@in@clist #1#2->\def \MT@res@a 
                                  ##1,#1,##2##3\@nnil {\ifx ##2\@empty \MT@i...
l.7 \author{ö}
               
? 
! Illegal parameter number in definition of \@xs@arg@ii.
<to be read again> 
                   1
l.7 \author{ö}
               
? 
```
I get the same error when using `\"o` instead of the UTF-8 character. I do not get the error when pasting the character into other commands, such as the affiliation one.

**Comment by krono** [comment] 2019-06-05 19:29
Hi Manuel, 
can you include `\listfiles` and produce a log?
This looks like a microtype issue…

**Comment by mrigger** [comment] 2019-06-05 19:42
Hi Tobias,

I attached the file list below:

```
 *File List*
  acmart.cls    2019/05/27 v1.61 Typesetting articles for the Association for C
omputing Machinery
 xkeyval.sty    2014/12/03 v2.7a package option processing (HA)
 xkeyval.tex    2014/12/03 v2.7a key=value parser (HA)
 xstring.sty    2013/10/13  v1.7c  String manipulations (C Tellechea)
  amsart.cls    2017/10/31 v2.20.4
 amsmath.sty    2017/09/02 v2.17a AMS math features
 amstext.sty    2000/06/29 v2.01 AMS text
  amsgen.sty    1999/11/30 v2.0 generic functions
  amsbsy.sty    1999/11/29 v1.2d Bold Symbols
  amsopn.sty    2016/03/08 v2.02 operator names
    umsa.fd    2013/01/14 v3.01 AMS symbols A
amsfonts.sty    2013/01/14 v3.01 Basic AMSFonts support
microtype.sty    2018/01/14 v2.7a Micro-typographical refinements (RS)
microtype-pdftex.def    2018/01/14 v2.7a Definitions specific to pdftex (RS)
microtype.cfg    2018/01/14 v2.7a microtype main configuration file (RS)
etoolbox.sty    2018/08/19 v2.5f e-TeX tools for LaTeX (JAW)
booktabs.sty    2016/04/27 v1.618033 publication quality tables
refcount.sty    2016/05/16 v3.5 Data extraction from label references (HO)
 ltxcmds.sty    2016/05/16 v1.23 LaTeX kernel commands for general use (HO)
infwarerr.sty    2016/05/16 v1.4 Providing info/warning/error messages (HO)
totpages.sty    2005/09/19 v2.00 Totpages Package (muewi)
everyshi.sty    2001/05/15 v3.00 EveryShipout Package (MS)
 environ.sty    2014/05/04 v0.3 A new way to define environments
trimspaces.sty    2009/09/17 v1.1 Trim spaces around a token list
textcase.sty    2004/10/07 v0.07 Text only upper/lower case changing (DPC)
  natbib.sty    2010/09/13 8.31b (PWD, AO)
hyperref.sty    2018/02/06 v6.86b Hypertext links for LaTeX
hobsub-hyperref.sty    2016/05/16 v1.14 Bundle oberdiek, subset hyperref (HO)
hobsub-generic.sty    2016/05/16 v1.14 Bundle oberdiek, subset generic (HO)
  hobsub.sty    2016/05/16 v1.14 Construct package bundles (HO)
ifluatex.sty    2016/05/16 v1.4 Provides the ifluatex switch (HO)
  ifvtex.sty    2016/05/16 v1.6 Detect VTeX and its facilities (HO)
 intcalc.sty    2016/05/16 v1.2 Expandable calculations with integers (HO)
   ifpdf.sty    2017/03/15 v3.2 Provides the ifpdf switch
etexcmds.sty    2016/05/16 v1.6 Avoid name clashes with e-TeX commands (HO)
kvsetkeys.sty    2016/05/16 v1.17 Key value parser (HO)
kvdefinekeys.sty    2016/05/16 v1.4 Define keys (HO)
pdftexcmds.sty    2018/01/30 v0.27 Utility functions of pdfTeX for LuaTeX (HO)
pdfescape.sty    2016/05/16 v1.14 Implements pdfTeX's escape features (HO)
bigintcalc.sty    2016/05/16 v1.4 Expandable calculations on big integers (HO)
  bitset.sty    2016/05/16 v1.2 Handle bit-vector datatype (HO)
uniquecounter.sty    2016/05/16 v1.3 Provide unlimited unique counter (HO)
letltxmacro.sty    2016/05/16 v1.5 Let assignment for LaTeX macros (HO)
 hopatch.sty    2016/05/16 v1.3 Wrapper for package hooks (HO)
xcolor-patch.sty    2016/05/16 xcolor patch
atveryend.sty    2016/05/16 v1.9 Hooks at the very end of document (HO)
atbegshi.sty    2016/06/09 v1.18 At begin shipout hook (HO)
 hycolor.sty    2016/05/16 v1.8 Color options for hyperref/bookmark (HO)
 ifxetex.sty    2010/09/12 v0.6 Provides ifxetex conditional
 auxhook.sty    2016/05/16 v1.4 Hooks for auxiliary files (HO)
kvoptions.sty    2016/05/16 v3.12 Key value format for package options (HO)
  pd1enc.def    2018/02/06 v6.86b Hyperref: PDFDocEncoding definition (HO)
hyperref.cfg    2002/06/06 v1.2 hyperref configuration of TeXLive
   puenc.def    2018/02/06 v6.86b Hyperref: PDF Unicode definition (HO)
     url.sty    2013/09/16  ver 3.4  Verb mode for urls, etc.
 hpdftex.def    2018/02/06 v6.86b Hyperref driver for pdfTeX
rerunfilecheck.sty    2016/05/16 v1.8 Rerun checks for auxiliary files (HO)
graphicx.sty    2017/06/01 v1.1a Enhanced LaTeX Graphics (DPC,SPQR)
graphics.sty    2017/06/25 v1.2c Standard LaTeX Graphics (DPC,SPQR)
    trig.sty    2016/01/03 v1.10 sin cos tan (DPC)
graphics.cfg    2016/06/04 v1.11 sample graphics configuration
  pdftex.def    2018/01/08 v1.0l Graphics/color driver for pdftex
  xcolor.sty    2016/05/11 v2.12 LaTeX color extensions (UK)
   color.cfg    2016/01/02 v1.6 sample color configuration
geometry.sty    2018/04/16 v5.8 Page Geometry
manyfoot.sty    2005/09/11 v1.10 Many Footnote Levels Package (NCC)
nccfoots.sty    2005/02/03 v1.2 NCC Footnotes Package (NCC)
   iftex.sty    2013/04/04 v0.2 Provides if(tex) conditional for PDFTeX, XeTeX,
 and LuaTeX
glyphtounicode.tex
    cmap.sty    2008/03/06 v1.0h CMap support: searchable PDF
 caption.sty    2018/05/01 v3.3-147 Customizing captions (AR)
caption3.sty    2018/05/27 v1.8a caption3 kernel (AR)
   float.sty    2001/11/08 v1.3d Float enhancements (AL)
 comment.sty    
textcomp.sty    2017/04/05 v2.0i Standard LaTeX package
  ts1enc.def    2001/06/05 v3.0e (jk/car/fm) Standard LaTeX file
  ts1enc.dfu    2018/04/05 v1.2c UTF-8 support for inputenc
fancyhdr.sty    2017/06/30 v3.9a Extensive control of page headers and footers
inputenc.sty    2018/04/06 v1.3b Input encoding file
 balance.sty    1999/02/23 4.3 (PWD)
  ts1cmr.fd    2014/09/29 v2.5h Standard LaTeX font definitions
    umsa.fd    2013/01/14 v3.01 AMS symbols A
    umsb.fd    2013/01/14 v3.01 AMS symbols B
  mt-cmr.cfg    2013/05/19 v2.2 microtype config. file: Computer Modern Roman (
RS)
 nameref.sty    2016/05/21 v2.44 Cross-referencing by name of section
gettitlestring.sty    2016/05/16 v1.5 Cleanup title references (HO)
    test.out
    test.out
supp-pdf.mkii
epstopdf-base.sty    2016/05/15 v2.6 Base part for package epstopdf
  grfext.sty    2016/05/16 v1.2 Manage graphics extensions (HO)
epstopdf-sys.cfg    2010/07/13 v1.3 Configuration of (r)epstopdf for TeX Live
  mt-msa.cfg    2006/02/04 v1.1 microtype config. file: AMS symbols (a) (RS)
  mt-msb.cfg    2005/06/01 v1.0 microtype config. file: AMS symbols (b) (RS)
 ***********
```

**Comment by borisveytsman** [comment] 2019-06-05 19:59
@krono I think it is not microtype.  The problem is probably here:
 ```
 \IfSubStr{#2}{,}{\ClassWarning{\@classname}{Do not put several
      authors in the same \string\author\space macro!}}{}%
```
(see definition of `\author`).  I remember there was a problem  LaTeX kernel, later fixed. 

I cannot reproduce the error with the current LaTeX kernel, so I am inclined to close this

**Comment by krono** [comment] 2019-06-05 20:02
Hmm, sounds reasonable.
However, Manuel indicates a TeXLive 2019, so he probably wont be the only one having this problem if it's present in the 2019 LaTeX kernel, I recon…

**Comment by borisveytsman** [comment] 2019-06-05 20:03
@mrigger What is the kernel version do you use?  The top of my log file says

`This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019) (preloaded format=pdflatex 2019.6.5)  5 JUN 2019 14:16`

What does your log say?

**Comment by borisveytsman** [comment] 2019-06-05 20:08
@krono I recently updated my installation...

**Comment by krono** [comment] 2019-06-05 20:09
I keep mine current, too.
But I don't think most authors would beyond the yearly checkpoints (OR the system updates, like Debian's…)

**Comment by borisveytsman** [comment] 2019-06-05 20:10
I can skip the warning if the current version of the kernel is too old...

**Comment by borisveytsman** [comment] 2019-06-05 20:11
Or maybe skip it altogether...

**Comment by krono** [comment] 2019-06-05 20:13
Let's wait for Manuel, I'd say.

But yes, I think skipping it would be good, because we would have issues with
```
\author{Frederic P. Brooks, Jr.}
```
for example…

**Comment by borisveytsman** [comment] 2019-06-05 20:14
Well, I generate a warning here...

**Comment by krono** [comment] 2019-06-05 20:15
Yeah, you're right. I also don't want to hold you up, just trying to give good input :)

**Comment by mrigger** [comment] 2019-06-05 20:20
@borisveytsman Here is my kernel version:

```
This is pdfTeX, Version 3.14159265-2.6-1.40.19 (TeX Live 2019/dev/Debian) (preloaded format=pdflatex 2019.5.25)  5 JUN 2019 20:27
```

**Comment by mrigger** [comment] 2019-06-06 08:54
I received some assistance from Conference Publishing, and they could not reproduce the issue on three kernels, including the one that I'm using:

```
pdfTeX 3.14159265-2.6-1.40.16 (TeX Live 2015/Debian)
pdfTeX 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian)
pdfTeX 3.14159265-2.6-1.40.19 (TeX Live 2019/dev/Debian)
```

So it seems that the problem is not (directly) related to the version of the kernel.

**Comment by krono** [comment] 2019-06-06 09:56
Can you give a try with `\errorcontextlines=999`?

**Comment by mrigger** [comment] 2019-06-06 12:47
Unexpectedly, the issue no longer appears after randomly installing the the `texlive-full` package. Before that, I still got a log with `\errorcontextlines=999`:

```
! Undefined control sequence.
\MT@in@clist #1#2->\def \MT@res@a 
                                  ##1,#1,##2##3\@nnil {\ifx ##2\@empty \MT@i...

\MT@register@subst@font ...ont@name \MT@font@list 
                                                  \ifMT@inlist@ \else \xdef ...

\pickup@font ...ame \else \MT@register@subst@font 
                                                  \fi \fi \MT@setupfont \end...

\MT@ltx@pickupfont ->\let \pickup@font 
                                       \MT@orig@pickupfont 
\add@accent #1#2->\MT@ltx@pickupfont 
                                     \MT@orig@add@accent {#1}{#2}\MT@MT@pick...

\@xs@assign #1#2->\@xs@def #1{#2
                                }
\@xs@IfSubStr@@ ...#1}\@xs@assign \@xs@arg@ii {#2}
                                                  \@xs@assign \@xs@arg@iii {...

\\author [#1]#2->\IfSubStr {#2}{,}
                                  {\ClassWarning {\@classname }{Do not put s...
l.7 \author{ö}
               
? 
! Emergency stop.
\MT@in@clist #1#2->\def \MT@res@a 
                                  ##1,#1,##2##3\@nnil {\ifx ##2\@empty \MT@i...

\MT@register@subst@font ...ont@name \MT@font@list 
                                                  \ifMT@inlist@ \else \xdef ...

\pickup@font ...ame \else \MT@register@subst@font 
                                                  \fi \fi \MT@setupfont \end...

\MT@ltx@pickupfont ->\let \pickup@font 
                                       \MT@orig@pickupfont 
\add@accent #1#2->\MT@ltx@pickupfont 
                                     \MT@orig@add@accent {#1}{#2}\MT@MT@pick...

\@xs@assign #1#2->\@xs@def #1{#2
                                }
\@xs@IfSubStr@@ ...#1}\@xs@assign \@xs@arg@ii {#2}
                                                  \@xs@assign \@xs@arg@iii {...

\\author [#1]#2->\IfSubStr {#2}{,}
                                  {\ClassWarning {\@classname }{Do not put s...
l.7 \author{ö}
               
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on test.log.
```

**Comment by krono** [comment] 2019-06-06 12:54
Then let's close as @borisveytsman suggests

**Closed** 2019-06-06 12:54 UTC

**Comment by matthias-g** [comment] 2019-07-22 13:42
For me the problem was solved after installing the package `newtx`.
