### ISSUE TITLE
typesetting of first author in (citekeys == [last name + year]) bibliography

### ISSUE THREAD

**Issue by jowens** [borisveytsman/acmart#154] opened 2017-05-03 23:27 UTC
Reported by my grad student @kseitz. 

@kseitz notes, and I agree, that the way the first author is typeset in the current ACM bibliographies is frustrating. I'm looking at the recently accepted ACM SIGGRAPH paper http://graphics.cs.cmu.edu/projects/shadercomp/he17_shadercomp.pdf . Let's say I am reading page 100:9 and see "Mark et al. 2003" and want to look up that reference. I turn to the bibliography, but the cite keys aren't listed in this format (there is no "Mark et al. 2003" tag). Even worse, "Mark" is not the first word of any entry. Instead the entry looks like:

> William R. Mark, R. Steven Glanville, Kurt Akeley, and Mark J. Kilgard. 2003. Cg: A System for Programming Graphics Hardware in a C-like Language. ACM Trans. Graph. 22, 3 (July 2003), 896–907.

So if I'm looking for this reference, I basically have to do a mental binary search on the reference list with the significant complication that in each entry, I have to scan right until I see the last name I'm looking for (or decide that it's not the right entry).

Many reference styles will set the reference as:

> [Mark et al. 2003] William R. Mark, R. Steven Glanville, Kurt Akeley, and Mark J. Kilgard. 2003. Cg: A System for Programming Graphics Hardware in a C-like Language. ACM Trans. Graph. 22, 3 (July 2003), 896–907.

but I appreciate the brevity of not having to list the cite key. But it would be much easier to find the entry I'm looking for if the first word in the citekey matched the first word in the associated reference. For the typical person-as-first-author case, I would consider typesetting the first author as {lastname, firstname}, even if the rest of the author list is {firstname lastname}.

> Mark, William R., R. Steven Glanville, Kurt Akeley, and Mark J. Kilgard. 2003. Cg: A System for Programming Graphics Hardware in a C-like Language. ACM Trans. Graph. 22, 3 (July 2003), 896–907.

**Comment by MatthewFluet** [comment] 2017-05-04 00:43
Duplicate of #145.

**Closed** 2024-09-01 00:12 UTC
